# Generated by Django 3.2 on 2021-04-16 14:32

from django.db import migrations

import django_tiptap.tiptap.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tiptap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=django_tiptap.tiptap.fields.TipTapTextField(),
        ),
    ]
