# Generated by Django 4.1.4 on 2022-12-09 10:55

from django.db import migrations, models

import django_tiptap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_tiptap.fields.TipTapTextField()),
            ],
        ),
    ]
